### ISSUE TITLE
Redundant conditional statements in 1.6.1.x

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/RHEL9-CIS#128]
**Describe the Issue**
[Here](https://github.com/ansible-lockdown/RHEL9-CIS/blob/8405e67db24ae0c2389ba5ba7312c02b687b3494/tasks/section_1/main.yml#L59C13-L59C37) it's specified that tasks in `cis_1.6.1.x.yml` file shall be included when SELinux is not disabled(`when: not rhel9cis_selinux_disable`):
```
- name: "SECTION | 1.6 | Mandatory Access Control"
  ansible.builtin.include_tasks:
      file: cis_1.6.1.x.yml
  when: not rhel9cis_selinux_disable
```
Therefore, any similar condition present on tasks in `file: cis_1.6.1.x.yml` like [this one](https://github.com/ansible-lockdown/RHEL9-CIS/blob/8405e67db24ae0c2389ba5ba7312c02b687b3494/tasks/section_1/cis_1.6.1.x.yml#L42) would be redundant:
```
- name: "1.6.1.3 | PATCH | Ensure SELinux policy is configured"
  ansible.posix.selinux:
      conf: /etc/selinux/config
      policy: "{{ rhel9cis_selinux_pol }}"
      state: "{{ rhel9cis_selinux_enforce }}"
  when:
      - not rhel9cis_selinux_disable
      - rhel9cis_rule_1_6_1_3
[...]
```

**Expected Behavior**
No redundant conditionals should be present. 

**Actual Behavior**
Redundant conditionals are present. 

**Control(s) Affected**
1.6.1.* rules

**Environment (please complete the following information):**

- branch being used: [e.g. devel]
[N/A]

**Additional Notes**
Anything additional goes here

**Possible Solution**
I'll add a PR immediately.
