### ISSUE TITLE
Inconsistent conditionals when masking services

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/RHEL9-CIS#135]
**Describe the Issue**
The way I understood rules 2.2.16, 2.2.17 and 2.2.18 is this one:
| Server  | Service | Result                                                                                 |
|---------|---------|---------------------------------------------------------------|
| false   | false   | **Remove 'package'**                                                             |
| false   | true    | Needing 'service' without needing 'server' makes no sense |
| true    | false   | **Mask 'service'**                                                                  |
| true    | true    | SKIP RULE, BOTH 'service' and 'server' are required             |

**Expected Behavior** (similar with [2.2.17](https://github.com/siemens/RHEL9-CIS/blob/8405e67db24ae0c2389ba5ba7312c02b687b3494/tasks/section_2/cis_2.2.x.yml#L309) or [2.2.18](https://github.com/siemens/RHEL9-CIS/blob/8405e67db24ae0c2389ba5ba7312c02b687b3494/tasks/section_2/cis_2.2.x.yml#L339))
```
      - name: "2.2.16 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked | mask service"
        ansible.builtin.systemd:
            name: nfs-server
            masked: true
            state: stopped
        when:
            - rhel9cis_use_nfs_server
            - not rhel9cis_use_nfs_service
```
          
**Actual Behavior**
```
      - name: "2.2.16 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked | mask service"
        ansible.builtin.systemd:
            name: nfs-server
            masked: true
            state: stopped
        when:
            - not rhel9cis_use_nfs_server
            - rhel9cis_use_nfs_service
```

**Control(s) Affected**
2.2.16

**Environment (please complete the following information):**

- branch being used: [e.g. devel]

**Possible Solution**
PR afterwards.
