### ISSUE TITLE
2.3.4 - Ensure FTP client is not installed - wrong conditional

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/RHEL9-CIS#137]
**Describe the Issue**
wrong variable used for 2.3.4.

**Expected Behavior**(`rhel9cis_FTP_client`)
```
- name: "2.3.4 | PATCH | Ensure FTP client is not installed"
  ansible.builtin.package:
      name: ftp
      state: absent
  when:
      - not rhel9cis_ftp_client
      - "'ftp' in ansible_facts.packages"
      - rhel9cis_rule_2_3_4
```

**Actual Behavior**(`rhel9cis_TFTP_client`)
```
- name: "2.3.4 | PATCH | Ensure FTP client is not installed"
  ansible.builtin.package:
      name: ftp
      state: absent
  when:
      - not rhel9cis_tftp_client
      - "'ftp' in ansible_facts.packages"
      - rhel9cis_rule_2_3_4
```
**Control(s) Affected**
2.3.4.

**Environment (please complete the following information):**
- branch being used: [e.g. devel]

**Possible Solution**
PR afterwards.
