### ISSUE TITLE
Wrong subsection name(rsyslog)

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/RHEL9-CIS#142]
**Describe the Issue**
wrong sub-section name

**Expected Behavior**
```
- name: "SECTION | 4.2.1 | Configure rsyslog"
  ansible.builtin.import_tasks:
      file: cis_4.2.1.x.yml
  when: rhel9cis_syslog == 'rsyslog'

- name: "SECTION | 4.2.2 | Configure journald"
  ansible.builtin.import_tasks:
      file: cis_4.2.2.x.yml
  when: rhel9cis_syslog == 'journald'
```

**Actual Behavior**
```
- name: "SECTION | 4.2 | Configure Logging"           # wrong name(should be "SECTION | 4.2.1 | Configure rsyslog")
  ansible.builtin.import_tasks:
      file: cis_4.2.1.x.yml
  when: rhel9cis_syslog == 'rsyslog'

- name: "SECTION | 4.2.2 | Configure journald"
  ansible.builtin.import_tasks:
      file: cis_4.2.2.x.yml
  when: rhel9cis_syslog == 'journald'
```

**Control(s) Affected**
4.2.1.*

**Environment (please complete the following information):**

- branch being used: [e.g. devel]

**Possible Solution**
PR.
