### ISSUE TITLE
rhel9cis_authselect['options']

### ISSUE THREAD

**Issue by ipruteanu-sie** [ansible-lockdown/RHEL9-CIS#144]
**Question**
What was the original intention of this dict variable:
```
rhel9cis_authselect:
    custom_profile_name: custom-profile
    default_file_to_copy: "sssd --symlink-meta"                            
    options: with-sudo with-faillock without-nullok                       *****
```

I totally agree that 5.4.2 rule [only mentions `with-faillock`](https://www.tenable.com/audits/items/CIS_CentOS_8_Server_v2.0.0_L1.audit:9b516ad2a87126c2b3a9df1ca3a29bfa).
```
      - name: "5.4.2 | PATCH | Ensure authselect includes with-faillock | Create custom profiles"
        ansible.builtin.shell: "authselect select custom/{{ rhel9cis_authselect['custom_profile_name'] }} with-faillock"
        when: rhel9cis_authselect_custom_profile_select
```

However, if I understand correctly the role of the option key-value pair: `options: with-sudo with-faillock without-nullok`, we could use it similarly [as in this Tenable example](https://www.tenable.com/audits/items/CIS_CentOS_8_Workstation_v2.0.0_L1.audit:0f95080d3c0f472a5ecbf89f99997051): **# authselect select custom/custom-profile with-sudo with-faillock without-nullok** :
```
      - name: "5.4.2 | PATCH | Ensure authselect includes with-faillock | Create custom profiles"
        ansible.builtin.shell: "authselect select custom/{{ rhel9cis_authselect['custom_profile_name'] }}  {{ rhel9cis_authselect['options'] }}"
        when: rhel9cis_authselect_custom_profile_select
```

**Environment (please complete the following information):**
N/A
