### ISSUE TITLE
Wrong filename in task 1.8.5

### ISSUE THREAD

**Issue by levaillx** [ansible-lockdown/RHEL9-CIS#255]
**Describe the Issue**
Missing suffix `_lock` to the dest filename. It is expected by the RHEL9-Audit control.

Currently in `tasks/section_1/cis_1.8.x.yml`:
```
      - name: "1.8.5 | PATCH | Ensure GDM screen locks cannot be overridden | Make lock file"
        ansible.builtin.template:
            src: etc/dconf/db/00-screensaver_lock.j2
            dest: "/etc/dconf/db/{{ rhel9cis_dconf_db_name }}.d/locks/00-screensaver"
```

**Control(s) Affected**
1.8.5

**Environment:**
- branch being used: devel, tag 1.3.2
