### ISSUE TITLE
Task 1.1.1 - Configure Filesystem Kernel Modules

### ISSUE THREAD

**Issue by msachikanta** [ansible-lockdown/RHEL9-CIS#285]
**Have you checked [ReadtheDocs](https://ansible-lockdown.readthedocs.io/en/latest/)?:**
Yes

**Describe the Issue**
Looks like `lineinfile` ansible module for tasks `1.1.1.1` to `1.1.1.9` are having wrong `line` as shown below:

For example, task 1.1.1.1

```
- name: "1.1.1.1 | PATCH | Ensure cramfs kernel module is not available | Edit modprobe config"
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/CIS.conf
        regexp: "^(#)?install cramfs(\\s|$)"
        line: "install cramfs /bin/true"
        create: true
        mode: 'go-rwx'
```

As per CIS Workbench documentation it should be `install squashfs /bin/false` as shown below:

<img width="826" alt="Image" src="https://github.com/user-attachments/assets/7e4d22f0-bd86-4747-ad77-88a2502296a4" />

Link to CIS workbench documentation - https://workbench.cisecurity.org/sections/2758812/recommendations/4466392

**Expected Behavior**
As per CIS workbench documentation, it should be `install squashfs /bin/false`

**Actual Behavior**
Its appearing as `install squashfs /bin/true` for all Filesystem Kernel Modules in ansible role.

**Control(s) Affected**
Following filesystem kernel modules controls are affected:
```
rhel9cis_rule_1_1_1_1
rhel9cis_rule_1_1_1_2
rhel9cis_rule_1_1_1_3
rhel9cis_rule_1_1_1_4
rhel9cis_rule_1_1_1_5
rhel9cis_rule_1_1_1_6
rhel9cis_rule_1_1_1_7
rhel9cis_rule_1_1_1_8
rhel9cis_rule_1_1_1_9
```

**Environment (please complete the following information):**

- branch being used: `devel`

**Additional Notes**
Its the same for all the ansible roles, such as `RHEL7-CIS`, `RHEL8-CIS`, `RHEL9-CIS`, `AMAZON2-CIS` and `AMAZON2023-CIS`.

**Possible Solution**
Replace `install squashfs /bin/true` with `install squashfs /bin/false` will fix the issue.
