### ISSUE TITLE
/root/.bash_profile should not have u+x permissions

### ISSUE THREAD

**Issue by dbsanders** [ansible-lockdown/RHEL9-CIS#296]
**Describe the Issue**
Caused by Lockdown 5.4.2.6 rule, where /root/.bash_profile is given 0700 permissions

Official CIS audit script fails on control 7.2.9 (Ensure local interactive user dot files access is configured)
```
- Audit Result:
  ** FAIL **
 - * Reasons for audit failure * :
 - User: "root" Home Directory: "/root"
  - File: "/root/.bash_profile" is mode: "0700" and should be mode: "644" or more restrictive
```

**Expected Behavior**
.bash_profile files do not want execute permission, it's unnecessary.
`-rw-------. 1 root root 152 Feb 14 14:13 /root/.bash_profile
`
**Actual Behavior**
`-rwx------. 1 root root 152 Feb 14 14:13 /root/.bash_profile
`
**Control(s) Affected**
5.4.2.6

**Environment (please complete the following information):**

- branch being used: release 2.0.0
- Ansible Version: core 2.17.8
- Host Python Version: 3.10.12
- Ansible Server Python Version: 3.10.12
- Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
#Just remove the u+x on the mode: line

```
- name: "5.4.2.6 | PATCH | Ensure root user umask is configured"
    when: rhel9cis_rule_5_4_2_6
  tags:
    - level1-server
    - level1-workstation
    - patch
    - shadow_suite
    - rule_5.4.2.6
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
  ansible.builtin.lineinfile:
    path: /root/.bash_profile
    regexp: \s*umask
    line: "umask {{ rhel9cis_root_umask }}"
    create: true
    #mode: 'u+x,go-rwx'
    mode: 'go-rwx'
```
