### ISSUE TITLE
Failure 5.3.7 | PATCH | Ensure access to the su command is restricted | wheel group contains root

### ISSUE THREAD

**Issue by adgantt** [ansible-lockdown/RHEL9-CIS#41]
Running the playbook fails on 5.3.7 | PATCH | Ensure access to the su command is restricted | wheel group contains root with error message:

```
fatal: [default]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: root. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}
```

**Expected Behavior**
Expect the task to complete successfully and not fail the playbook run.

**Actual Behavior**
Playbook fails 

**Control(s) Affected**
5.3.7 

**Environment (please complete the following information):**

- branch being used: [e.g. devel] 
-- devel
- Ansible Version: [e.g. 2.10] 
-- ansible [core 2.14.1]
- Host Python Version: [e.g. Python 3.7.6]
-- python version = 3.11.2 (v3.11.2:878ead1ac1, Feb  7 2023, 10:02:41) [Clang 13.0.0 (clang-1300.0.29.30)] 
- Ansible Server Python Version: [e.g. Python 3.7.6]
-- N/A
- Additional Details:

**Additional Notes**
Running off source AMI RHEL-9.1.0_HVM-20221101-arm64-2-Hourly2-GP2, ami-05c5c474dfb6af922

**Possible Solution**
Change literal string `rhel9cis_sugroup_users: "root"` to array values `rhel9cis_sugroup_users: [ "root" ]`

**Comment by uk-bolly** [comment]
hi @adgantt 

Thank you for taking the time to raise this issue. While i was unable to reproduce the issue using the devel branch and 2.13. I have rewritten the control and tidied it up. The PR is now open.

Aiming to get this PR in asap.

Thanks again

uk-bolly

**Comment by boris-stojnev** [comment]
Hi @uk-bolly ,

Not sure what's the reason behind forcing to specify su group, but if we go with default wheel it will remove all users from su group (wheel).

What do you think of having something like this, and returning `rhel9cis_sugroup_users` var

```yaml
- name: "5.3.7 | PATCH | Ensure access to the su command is restricted | remove users from group"
        ansible.builtin.lineinfile:
            path: /etc/group
            regexp: '^{{ rhel9cis_sugroup }}(:.:.*:{{ rhel9cis_sugroup_users }}).*$'
            line: '{{ rhel9cis_sugroup }}\g<1>'
            backrefs: true
```
Original devel code https://github.com/ansible-lockdown/RHEL9-CIS/blob/devel/tasks/section_5/cis_5.3.x.yml

Now, there is no task of specifying sugroup users, which may be a problem.
