### ISSUE TITLE
Audit fails with syntax error on ARM64

### ISSUE THREAD

**Issue by lucab85** [ansible-lockdown/RHEL9-CIS#77]
**Describe the Issue**
The CIS audit fails with a syntax error on a fresh RHEL 9.2 machine on ARM64 architecture.

**Expected Behavior**
I expect the audit result of the CIS benchmark.

**Actual Behavior**
```
TASK [RHEL9-CIS : Pre Audit | Capture pre-audit result] *********************************
fatal: [rhel.example.com]: FAILED! => {"msg": "the field 'args' has an invalid value ({'pre_audit_summary': '{{ pre_audit.stdout | from_json | json_query(summary) }}'}), and could not be converted to an dict.The error was: Expecting value: line 1 column 1 (char 0)\n\nThe error appears to be in '/Users/lberton/.ansible/roles/RHEL9-CIS/tasks/pre_remediation_audit.yml': line 90, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Pre Audit | Capture pre-audit result\n    ^ here\n"}
```

**Control(s) Affected**
What controls are being affected by the issue

**Environment (please complete the following information):**

- branch being used: main
- Ansible Version: ansible [core 2.15.2]
- Host Python Version: Python 3.9.16
- Ansible Server Python Version: python version = 3.11.4
- Additional Details:

**Additional Notes**

audit.yml Playbook
```
---
- name: RHEL9 CIS Audit
  hosts: all
  become: true
  roles:
    - name: "RHEL9-CIS"
      vars:
        setup_audit: true
        run_audit: true
```

host:
```
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
```

**Possible Solution**
Fix the syntax error in `pre_remediation_audit.yml`

**Comment by lucab85** [comment]
Workaround Playbook:

```
---
- name: RHEL9 CIS Audit
  hosts: all
  become: true
  roles:
    - name: "RHEL9-CIS"
      vars:
        setup_audit: true
        run_audit: true
        goss_url: https://github.com/goss-org/goss/releases/download/v0.3.23/goss-linux-arm64
        goss_version:
          release: v0.3.23
          checksum: 'sha256:7b0794fa590857e7d64ef436e1a100ca26f6039f269a6138009aa837d27d7f9e'

```
