### ISSUE TITLE
Error due to missing jmespath

### ISSUE THREAD

**Issue by agbrowne** [ansible-lockdown/RHEL9-CIS#80]
**Describe the Issue**
When the run gets to 'RHEL9-CIS : 6.1.13 | AUDIT | Audit SUID executables | Alert SUID executables exist' an error is thrown as follows... 

fatal: [machine.example.com]: FAILED! => 
  msg: You need to install "jmespath" prior to running json_query filter

**Expected Behavior**
The job runs with no errors

**Actual Behavior**
An error is thrown as above

**Control(s) Affected**
6.1.13 | AUDIT | Audit SUID executables | Alert SUID executables exist'

**Environment (please complete the following information):**

- branch being used: main
- Ansible Version: core 2.14.2
- Host Python Version: 3.9.16
- Ansible Server Python Version: 3.11.2 (from 'ansible --version')
- Additional Details:
Both platforms: AlmaLinux 9

**Additional Notes**
I have tried installing the following on the Ansible server:
- pip install -r requirements.txt
- dnf install python3-jmespath

Installed Ansible collections are as follows...
```
Collection        Version
----------------- -------
ansible.posix     1.5.4  
community.general 7.2.1
```
This wasn't an issue when I was using the devel branch by mistake.

I don't want to install any additional packages (pip or RPM) on the target host in order to make this work.

**Possible Solution**
Don't use json\_query, or provide details as to what packages are required.

**Comment by agbrowne** [comment]
The file containing the erroneous code is cis_6.1.x.yml

The code in main (with the error) is:

```
      - name: "6.1.13 | AUDIT | Audit SUID executables | Alert SUID executables exist"
        ansible.builtin.debug:
            msg: "Warning!! SUID set on items in {{ rhel_09_6_1_13_suid_perms | json_query('results[*].stdout_lines[*]') | flatten }}"
        when: rhel9_6_1_13_suid_found
```
The code in devel (which works) is:

```
      - name: "6.1.13 | AUDIT | Audit SUID executables | Alert SUID executables exist"
        ansible.builtin.debug:
            msg: "Warning!! Manual intervention is required -- SUID set on items in {{ item.item.mount }}: {{ item.stout_lines | join(', ') }}"
        loop: "{{ rhel_09_6_1_13_perms_results.stdout_lines }}"
        when:
            - rhel_09_6_1_13_perms_results.stdout is defined
```
